spring:
  application:
    name: ms-users
  datasource:
    url: jdbc:postgresql://db.tfglbsxvqtshorsvxrto.supabase.co:5432/postgres
    username: postgres
    password: petoneDB2026
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true